import = [ "~/.config/alacritty/dracula.toml" ]

[window]
dynamic_padding = false

  [window.padding]
  x = 15
  y = 15

[font]
size = 10

  [font.normal]
  family = "Iosevka"
  style = "Normal"

  [font.bold]
  family = "Iosevka"
  style = "Bold"

  [font.italic]
  family = "Iosevka"
  style = "Light Italic"

